[config]
ch1_day = 10.0
ch1_half_cycles = 0
ch1_night = 10.0
ch1_overtime = 0.0
ch2_day = 180.0
ch2_half_cycles = 6
ch2_night = 180.0
ch2_overtime = 180.0
ch3_day = 180.0
ch3_half_cycles = 6
ch3_night = 180.0
ch3_overtime = 180.0
ch4_day = 180.0
ch4_half_cycles = 6
ch4_night = 180.0
ch4_overtime = 180.0
verbose = true
